name = "soc-log-analyzer"
main = "src/index.ts"
compatibility_date = "2025-08-27"

[[r2_buckets]]
binding = "LOG_STORAGE"
bucket_name = "soc-log-files"

[ai]
binding = "AI"

# Development overrides
[env.development]
[[env.development.r2_buckets]]
binding = "LOG_STORAGE"
bucket_name = "soc-log-files"

[env.development.ai]
binding = "AI"

[env.development.vars]
AUTH_USERNAME = "admin"
AUTH_PASSWORD = "devpassword"

# Production settings
[env.production]
[[env.production.r2_buckets]]
binding = "LOG_STORAGE"
bucket_name = "soc-log-files"

[env.production.ai]
binding = "AI"

[env.production.vars]
AUTH_USERNAME = "soc_admin"