name = "soc-log-analyzer-ui"
compatibility_date = "2025-08-27"

# Pages configuration
pages_build_output_dir = "out"

[env.production.vars]
# Backend URL for production deployment
NEXT_PUBLIC_API_URL = "https://soc-log-analyzer.stephen-lamari.workers.dev"

# Optional preview environment
[env.preview.vars]
NEXT_PUBLIC_API_URL = "https://soc-log-analyzer.stephen-lamari.workers.dev"